import uuid
from datetime import datetime, timezone

from sqlalchemy import String, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Notification(Base):
    """
    Represents a notification for the student.

    Notifications are generated by the system based on the student's
    academic data. They alert the student to things that need attention.

    Notification types:
    - deadline: an assignment or task deadline is approaching
    - exam: an exam is approaching
    - missed_session: a study session was missed
    - conflict: a scheduling conflict was detected
    - weekly_review: weekly review is ready
    - general: general information

    linked_item_type and linked_item_id point to the specific
    item that triggered this notification, so the frontend can
    navigate to it directly.
    """
    __tablename__ = "notifications"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )

    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Notification content
    notification_type: Mapped[str] = mapped_column(String(50), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)

    # Read status
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Optional link to the item that triggered this notification
    linked_item_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    linked_item_id: Mapped[str | None] = mapped_column(String(36), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationship
    user: Mapped["User"] = relationship("User", back_populates="notifications")  # type: ignore

    def __repr__(self) -> str:
        return f"<Notification id={self.id} type={self.notification_type} read={self.is_read}>"