"""add timetable entries table

Revision ID: 8d2fbababb36
Revises: 3baff0017c6e
Create Date: 2026-09-27 13:21:58.319788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2fbababb36'
down_revision: Union[str, Sequence[str], None] = '3baff0017c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('lecturer', sa.String(length=255), nullable=True),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_course_id'), 'timetable_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_user_id'), 'timetable_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_user_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    # ### end Alembic commands ###
