"""add study preferences table

Revision ID: e320594b12ac
Revises: c1a2b3c4d5e6
Create Date: 2026-10-03 10:41:53.042921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e320594b12ac'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('study_time', sa.String(length=20), nullable=False),
    sa.Column('study_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('session_length_minutes', sa.Integer(), nullable=False),
    sa.Column('break_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_preferences_user_id'), 'study_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_preferences_user_id'), table_name='study_preferences')
    op.drop_table('study_preferences')
    # ### end Alembic commands ###
